# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 02:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0003_auto_20160415_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='username',
        ),
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.URLField(max_length=512),
        ),
    ]
